name: tha_player
description: "Native network-only video player with custom Android (ExoPlayer) and iOS (AVPlayer) engines."
version: 0.5.1
homepage: https://github.com/thethtwe-dev/tha_player
repository: https://github.com/thethtwe-dev/tha_player
issue_tracker: https://github.com/thethtwe-dev/tha_player/issues
topics:
  - video
  - player
  - media
  - drm
  - thumbnails

environment:
  sdk: ^3.10.4
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  
  # No third-party Flutter playback plugins; we use native code via platform views
  cupertino_icons: ^1.0.8
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:

  plugin:
    platforms:
      android:
        package: com.example.tha_player
        pluginClass: ThaPlayerPlugin
      ios:
        pluginClass: ThaPlayerPlugin
        
  assets:
    - assets/
  
